### 6.5.2 try语句块

【格式】try语句的通用语法

```C++
try {
    program_statements
}catch (exception-declaration){
    handler-statements
}catch (exception-declaration){
    handler-statement
} // ...
```

#### try语句

* 每一个子句对应一个花括号
* try：内部语句用于组成程序的正常逻辑
  * 注意：try语句中定义的对象作用域仅在块内，不能在catch中进行访问
* catch：组成：关键字catch、括号内一个对象的声明（**异常声明**）、异常发生执行语句

#### 编写处理代码

```C++
while(true){    
	try{
        if(item1.isbn() != item2.isbn)
            throw runtime_error("data must refer to same ISBN");
    } catch(runtime_error err){
        cout << err.what()
    }
}
```

* 运行原理：throw负责抛出异常，catch负责获得异常并处理
* err.what：每个标准异常类都定义了一个what成员函数，返回const char*

#### 异常的执行路径（多个try）

* 逐层向外寻找适合的catch语句
* 如果都没有，则转化到名为`terminate` 的标准库函数，将导致程序分正常退出

#### 编写异常安全的代码非常困难

